export const words = [
    {
        id: 0,
        name: 'UI/UX',
        top: '0px',
        delay: '1s',
    },
    {
        id: 1,
        name: 'Responsive design',
        top: '300px',
        delay: '1s',
    },
    {
        id: 2,
        name: 'Communication',
        top: '100px',
        delay: '0s',
    },
    {
        id: 3,
        name: 'Layout',
        top: '400px',
        delay: '1s',
    },
    {
        id: 4,
        name: 'Quik learning',
        top: '150px',
        delay: '2s',
    },
    {
        id: 5,
        name: 'Team Work',
        top: '200px',
        delay: '.5s',
    },
    {
        id: 6,
        name: 'Stress tolerance',
        top: '350px',
        delay: '3s',
    },
    {
        id: 7,
        name: 'Clean code',
        top: '250px',
        delay: '3s',
    },
    {
        id: 8,
        name: 'Problem-solving',
        top: '50px',
        delay: '2.5s',
    },
    {
        id: 9,
        name: 'Do my best!',
        top: '450px',
        delay: '4s',
    },
    {
        id: 10,
        name: 'UI/UX',
        top: '300px',
        delay: '6s',
    },
    {
        id: 11,
        name: 'Responsive design',
        top: '150px',
        delay: '7s',
    },
    {
        id: 12,
        name: 'Communication',
        top: '400px',
        delay: '6.5s',
    },
    {
        id: 13,
        name: 'Layout',
        top: '100px',
        delay: '5s',
    },
    {
        id: 14,
        name: 'Quik learning',
        top: '450px',
        delay: '8.5s',
    },
    {
        id: 15,
        name: 'Team Work',
        top: '0px',
        delay: '6.5s',
    },
    {
        id: 16,
        name: 'Stress tolerance',
        top: '50px',
        delay: '8.5s',
    },
    {
        id: 17,
        name: 'Clean code',
        top: '350px',
        delay: '9s',
    },
    {
        id: 18,
        name: 'Problem-solving',
        top: '250px',
        delay: '8s',
    },
    {
        id: 19,
        name: 'with Love',
        top: '200px',
        delay: '4.5s',
    },
]