import { Fragment } from "react";

import { GetStaticProps, InferGetStaticPropsType } from "next";
import Head from "next/head";

import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import NavigationSub from "@components/sections/navigation";
import PreviewSub from "@components/sections/preview";
import AboutSub from "@components/sections/about";

import { HomeContainer } from "@components/styles/home.style";

const Home = (_props: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <Fragment>
      <Head>
        <title>Create Next Portolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavigationSub scrollHandler={() => {}} />
        <HomeContainer>
          <PreviewSub />
          <AboutSub />
        </HomeContainer>
      </main>
    </Fragment>
  );
};

export const getStaticProps: GetStaticProps<any> = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale ?? "en", ["common"])),
  },
});

export default Home;
